### PR TITLE
Remove `fs.readFileSync` for the package works on browser environment.

### PR DESCRIPTION
**Pull request by imcuttle**
Hi! I want to use it on browser, but `fs` is unavailable.

### CODE REVIEW

**Comment by revin** [comment]
oh, great idea, thanks! 🎉 🎉 🌮

**Comment by revin** [comment]
heh oops sorry @Flet I guess I should've read this more closely before I realized this was your fork. Oof. Revert as necessary.

**Comment by Flet** [comment]
@revin no worries! Thanks for supporting it! Treat this repo as your own :)

You have access to publish to npm as well! Feel free to publish.

**Comment by imcuttle** [comment]
Hey, Could you publish to npm?
Thanks!

**Comment by Flet** [comment]
No problem! 

Published as `markdown-it-github-headings@1.1.1`

**Pull request merged**
