### PR TITLE
Added prefix to href tag, closes #2

### LINKED ISSUE #2: Prefix should be auto added to href tag

### PR DESCRIPTION
**Pull request by niftylettuce**

### CODE REVIEW

**Comment by niftylettuce** [comment]
btw this is being used here https://github.com/shime/livedown - thank you 👍

**Comment by Flet** [comment]
Hello! Thanks for the pull request! 

Adding the prefix to the href would deviate from the way GitHub generates links, which we wouldn't want to do by default.

Github has a bit of code that runs similar to [marky-deep-links](https://github.com/Flet/marky-deep-links):
>generated heading DOM ids are prefixed with user-content- for security reasons. This package checks whether someone has clicked on an auto-generated id, and updates the URL fragment remove the prefix, and scrolls the page to the header. This also works at startup if someone links to an anchor from an external site.

I'd like to keep the current behavior the default to avoid breaking. Would you be OK with this being available via an option passed in? If you can make that change I will happily merge this and add you as a collaborator! :)

**Comment by Flet** [comment]
BTW, thanks for writing that [Ubuntu node.js hacker setup](http://niftylettuce.com/posts/linux-mint-ubuntu-nodejs-hacker-setup/) article way back when, it helped me out! :)

**Comment by Flet** [comment]
livedown looks cool! I would love to have it wrapped in electron to replace vmd (since vmd deviates from github's behavior).

**Comment by niftylettuce** [comment]
Wow @Flet I did not know that about `user-content` and their DOM on the fly hashchange update.  So cool.  Nice package btw, will definitely use that in my work.

**Comment by niftylettuce** [comment]
We should instead document that <https://github.com/Flet/marky-deep-links> should be used.

**Comment by Flet** [comment]
Its mentioned in the README but maybe its not prominent enough?

**Comment by niftylettuce** [comment]
Yeah I was confused a bit at first, but at least it's there.  If you think moving to another place in Readme or bumping it up or putting it in a blockquote `> Text...` that might work, not sure.

**Comment by niftylettuce** [comment]
@Flet I'm writing a follow up, 4 year anniversary post to that blog article <http://niftylettuce.com/posts/linux-mint-ubuntu-nodejs-hacker-setup/>.  Follow me on Twitter @niftylettuce or send me a message at niftylettuce@gmail.com and I'll send you a link to it once it's up! ❤️

**Pull request closed without merging**
